# deploy config
apiVersion: apps/v1
kind: Deployment
metadata:
  name: giotto-gateway-admin
spec:
  replicas: 1
  selector:
    matchLabels:
      name: giotto-gateway-admin
  template:
    metadata:
      labels:
        name: giotto-gateway-admin
    spec:
      containers:
        - name: giotto-gateway-admin
          image: giotto-gateway-admin:84c9838
          imagePullPolicy: Never
          ports:
            - containerPort: 8880
---
# service config
apiVersion: v1
kind: Service
metadata:
  name: giotto-gateway-admin
spec:
  ports:
    - port: 8880
      name: "admin"
      targetPort: 8880
      protocol: TCP
      nodePort: 30888
  type: NodePort
  selector:
    name: giotto-gateway-admin